### ISSUE TITLE
extend

### ISSUE THREAD

**Issue by TrySound** [jonathantneal/postcss-write-svg#1]
util._extend is unofficial api. Suggest to replace it with object-assign module

**Comment by jonathantneal** [comment]
Is there a more detailed argument against using it? Also, would it be safe to look for [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) and expect support for that to arrive before `_extend` would be retired?

``` js
var assign = Object.assign || require('util')._extend;
```

**Comment by TrySound** [comment]
@jonathantneal I meant [this ponyfill](https://github.com/sindresorhus/object-assign)

**Comment by TrySound** [comment]
@jonathantneal Unofficial api doesn't give guarantee that it won't be removed.

**Comment by jonathantneal** [comment]
Good to know for future use. I did not actually need to use extend / assign at all, so it has been removed.
