### ISSUE TITLE
Dependency issue with postcss-write-svg

### ISSUE THREAD

**Issue by airen** [jonathantneal/postcss-write-svg#13]
I run the postcss-write-svg.  And I get this error:

```
Your current PostCSS version is 4.1.16, but postcss-write-svg uses 5.0.10. Perhaps this is the source of the error below.

events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function

```

**Comment by jonathantneal** [comment]
I believe you can resolve this by updating PostCSS In your build process.

postcss-write-svg requires [PostCSS v5](https://github.com/jonathantneal/postcss-write-svg/blob/master/package.json#L32). This error means that you are attempting to run the plugin with an older, incompatible version of PostCSS.

Let me know if it resolves the issue for you.
