### ISSUE TITLE
Add Warning about using old syntax

### ISSUE THREAD

**Issue by MadLittleMods** [jonathantneal/postcss-write-svg#16]
Add an option to warn the user about using the old syntax from `v1`.
- Detect any anonymous `@svg` at-rules
- Detect when nesting elements like `path`, `rect` without the `@`

I understand the major version change brings breaking changes but I think this could be useful to ease the transition.

**Comment by jonathantneal** [comment]
I think it’s been so long, and people only really adopted this in v2 that I can let it go. Objections?

**Comment by MadLittleMods** [comment]
Most likely no issue to let it go. Still will be jarring for projects who haven't upgraded but I guess it is to be expected for not keeping packages up to date.
