### ISSUE TITLE
Unknown CSS at-rule, Invalid property value

### ISSUE THREAD

**Issue by zhaoyu69** [jonathantneal/postcss-write-svg#21]
I want to fix 1px  in retina.
Npm package has been installed.(v3.0.1)
Required this package in postcss-loader options.
![image](https://user-images.githubusercontent.com/23548734/45524266-254b4200-b800-11e8-83ec-5d1fe36973bd.png)
But @svg error: Unknown CSS at-rule.
![image](https://user-images.githubusercontent.com/23548734/45524185-b53cbc00-b7ff-11e8-9ff5-792d88bca33a.png)
After running, warning: Invalid property value.
![image](https://user-images.githubusercontent.com/23548734/45524337-78bd9000-b800-11e8-9b26-a2c3f9bfc499.png)
Thanks for you help !

**Comment by jonathantneal** [comment]
This is an issue with your linter. This project uses non-standard syntax to create SVGs. You’d have to resolve this in your linter.
