### ISSUE TITLE
Can you provide an option to encode as base64?

### ISSUE THREAD

**Issue by smlombardi** [jonathantneal/postcss-write-svg#7]
I've found the the IE browsers will not display SVG embedded in CSS like this.

I've had to take my SVG, convert to base64, and then change where you have `utf-8` to `base64` to be able to really use SVG in CSS.

**Comment by MadLittleMods** [comment]
:+1:

Also have an option to add both so it acts as a fallback. Perhaps this kind of syntax:

```
require('postcss-write-svg')({
    encoding: 'base64'
});

require('postcss-write-svg')({
    encoding: [
        'utf8',
        'base64'
    ]
});
```

**Comment by jonathantneal** [comment]
This is now handled in v2.0.0
