### ISSUE TITLE
I want to use an inline svg as just one of a number of background images

### ISSUE THREAD

**Issue by joeldrapper** [jonathantneal/postcss-write-svg#8]
Is there any way to do this?

**Comment by artlantis** [comment]
visit this thread : http://stackoverflow.com/questions/10768451/inline-svg-in-css

**Comment by MadLittleMods** [comment]
@joeldrapper This is currently not possible. Stay tuned to #4 as the new syntax will allow for this use case.

**Comment by joeldrapper** [comment]
@MadLittleMods thank you. I'll keep an eye on that.
